-- Migration: articles
--
-- PRIMARY CHANGE: introduces the news_articles table and related indexes.
-- (DDL generated by Prisma when the NewsArticle model was added to schema.prisma.)
--
-- BUNDLED FIX: aligns DEFAULT CURRENT_TIMESTAMP on the updated_at columns of
-- page_sections and rubrics. These defaults were omitted from their original
-- migration DDL (20260302123207_init), which meant Prisma's @updatedAt field
-- could not rely on the database-level default as a fallback. The issue was
-- discovered while auditing all timestamp columns during the NewsArticle
-- implementation; fixing it here avoids an extra one-liner migration PR.
--
-- NOTE: body_tsv is a GENERATED ALWAYS column added by
-- 20260309000002_add_news_fts and must not be re-created here.

-- Align DEFAULT CURRENT_TIMESTAMP on updatedAt columns
ALTER TABLE "page_sections" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "rubrics"       ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
